# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mguerga <mguerga@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/14 11:40:19 by mguerga           #+#    #+#              #
#    Updated: 2024/09/12 14:02:55 by mguerga          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #
#laulau le nullos ^^
#version: '3.3' #PK ??
services:
  postgres:
    container_name: postgres
    env_file: "./backend/.env"
    build: backend/postgres/
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - backend_nw
    restart: on-failure

  django:
    container_name: django 
    env_file: "./backend/.env"
    build: backend/django/
    networks:
      - backend_nw
    restart: on-failure
    depends_on:
      - postgres
    ports:
      - 8000:8000

  nginx:
    container_name: nginx 
    build: backend/nginx/
    networks:
      - backend_nw
    ports:
      - 443:443
    restart: on-failure
    depends_on:
      - django 
    volumes:
      - ./frontend/:/var/www/frontend/
      - ./backend/staticfiles/:/var/www/backend/staticfiles/
      - ssl-certs:/etc/nginx/ssl
    
  game:
    container_name: game
    build:
      context: ./frontend/js/game/
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - 3000:3000
    networks:
      - backend_nw
    volumes:
      - ssl-certs:/etc/nginx/ssl
    depends_on:
      - nginx

networks:
  backend_nw:
    name: backend_nw

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: $HOME/data/db
  ssl-certs:
    driver : local
