# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    docker-compose.yaml                                :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mguerga <mguerga@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/07/14 11:40:19 by mguerga           #+#    #+#              #
#    Updated: 2024/07/30 11:42:13 by mguerga          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

#version: '3.3' #PK ??
services:

  postgres:
    container_name: postgres
    env_file: "./backend/.env"
    build: backend/postgres/
    volumes:
      - db_vol:/var/lib/postgresql/data
    networks:
      - backend_nw
    restart: on-failure

  django:
    container_name: django 
    env_file: "./backend/.env"
    build: backend/django/
    networks:
      - backend_nw
    ports:
      - "8000:8000"
    restart: on-failure
    depends_on:
      - postgres

networks:
  backend_nw:

volumes:
  db_vol:
    driver: local
    driver_opts:
      type: none
      o: bind
      device: /home/$USER/data/db
