# **************************************************************************** #
#                                                                              #
#                                                         :::      ::::::::    #
#    dockerfile                                         :+:      :+:    :+:    #
#                                                     +:+ +:+         +:+      #
#    By: mguerga <mguerga@42lausanne.ch>            +#+  +:+       +#+         #
#                                                 +#+#+#+#+#+   +#+            #
#    Created: 2024/08/02 18:05:59 by mguerga           #+#    #+#              #
#    Updated: 2024/08/05 12:16:29 by mguerga          ###   ########.fr        #
#                                                                              #
# **************************************************************************** #

FROM nginx:1.27.0-alpine 

COPY create_certs.sh /.

RUN apk add --no-cache openssl && \
	rm /etc/nginx/conf.d/default.conf && \
	sh /create_certs.sh	

COPY nginx.conf /etc/nginx/conf.d/
